<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */

$env = getenv('REDIRECT_APP_ENV') ?: 'production';

return array(
    'modules' => array(
        'GkSmarty',
        'AssetManager',
        'Columnis'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            sprintf('config/autoload/{,*.}{global,%s,local}.php', $env)
        ),
        'config_cache_enabled' => ($env == 'production'),
        'config_cache_key' => 'config-cache', 
        'module_map_cache_enabled' => ($env == 'production'),
        'module_map_cache_key' => 'module-map', 
        'cache_dir' => 'data/cache/module',
        'check_dependencies' => ($env != 'production'),
    )
);