<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */

$env = getenv('APP_ENV') ? : getenv('REDIRECT_APP_ENV') ? : 'production';

$conf = array(
    'service_manager' => array(
        'factories' => array(
            'ModuleManager' => 'ConditionalLoader\Service\Factory\ModuleManagerFactory',
        ),
        'invokables' => array(
            'AssetManagerResolver' => 'ColumnisExpress\ConditionResolver\AssetManagerResolver'
        )
    ),
    'modules' => array(
        'ZF\Apigility',
        'ZF\Apigility\Provider',
        'ZF\ApiProblem',
        'ZF\MvcAuth',
        'ZF\OAuth2',
        'ZF\Hal',
        'ZF\ContentNegotiation',
        'ZF\ContentValidation',
        'ZF\Rest',
        'ZF\Rpc',
        'ZF\Versioning',
        'ZfrCors',
        'AssetManager',
        'GkSmarty',
        'Columnis',
        'ExpressApi'
    ),
    'modules_condition_resolvers' => array(
        //'AssetManager' => 'AssetManagerResolver',
        //'GkSmarty' => 'GkSmartyResolver'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor'
        ),
        'config_glob_paths' => array(
            sprintf('config/autoload/{,*.}{global,%s,local}.php', $env)
        ),
        'config_cache_enabled' => ($env == 'production'),
        'config_cache_key' => 'config-cache',
        'module_map_cache_enabled' => ($env == 'production'),
        'module_map_cache_key' => 'module-map',
        'cache_dir' => 'data/cache/module',
        'check_dependencies' => ($env != 'production'),
    )
);

return $conf;